### ISSUE TITLE
Documentation files

### ISSUE THREAD

**Issue by RoxanneSHS** [Gibberlings3/SoD-to-BG2EE-Item-Upgrade#12]
Will it be possible to move all the md-files into a "documents"(or other name) folder inside the mod? If you extract the mod to the game, they all go into the main game directory. Also they overwrite files from other mods and/or get overwritten.

**Comment by mike1072** [comment]
The .md files are not included in the official download packages.  Make sure you are downloading one of the packages from the [latest release](https://github.com/Gibberlings3/SoD-to-BG2EE-Item-Upgrade/releases/latest) rather than the source code or master branch.

**Comment by RoxanneSHS** [comment]
They should be included, that is the point to have them in a subfolder.

**Comment by mike1072** [comment]
They are converted to .html files which ARE included.

**Comment by RoxanneSHS** [comment]
Right, but only if you use the self-installing exe from the the release. If you use the zip-file, then no.
Anyway, it was intended as a suggestion for improvement, so never mind.

**Comment by mike1072** [comment]
The HTML files are present in the Windows .exe, MacOS .zip, and Linux .zip releases.

The idea is that players should not be downloading the source code directly.  At G3, we've always advised players to download the appropriate package for their operating system, for several reasons:

- The packages contain only the files needed for installation (no unnecessary .gitignore, package_mod.bat, .md files, or utilities for other operating systems)
- The packages include a copy of WeiDU for the appropriate OS so the mod can be installed easily

The Markdown-to-HTML conversion is something new we're trying out, so that we can maintain the mod documentation in a single format and have it easily viewable both on GitHub and with the files included in the mod download.

It's still a work-in-progress, so if you have any other suggestions, feel free to direct them to the [topic at G3](https://www.gibberlings3.net/forums/topic/26717-g3-mod-packaging-made-easy/).
